# Generated by Django 4.2.7 on 2023-11-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('producer', models.CharField(max_length=30)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=200)),
                ('quantity', models.FloatField()),
            ],
        ),
    ]
