# Generated by Django 4.2.7 on 2023-11-02 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('agro', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Movie',
            new_name='Product',
        ),
    ]
